export type TeamMember = {
  role: string; name: string; initials: string; color: string; bg: string
  engagement: string; last_action: string; carrying_signal: string; notes: string
}
export type VendorItem = { vendor_type: string; status: string; note: string }
export type DecisionMaker = { name: string; role: string; authority: string }
export type ActionItem = { text: string; priority: 'critical' | 'important' | 'routine' }
export type Message = {
  sender: string; role: string; initials: string; color: string; bg: string
  time: string; body: string; negative: boolean
}
export type RiskVector = { label: string; severity: string }

export type StaticPID = {
  pid: string
  couple: string
  statusLevel: 'critical' | 'attention' | 'healthy'
  statusText: string
  risk_vectors: RiskVector[]
  analysis: string[]
  team_status: TeamMember[]
  comms: {
    client_chattiness: number; client_chattiness_label: string
    last_client_message: string; off_channel_indicator: boolean
    open_commitments: number; open_commitments_detail: string[]
  }
  vendor_coverage: VendorItem[]
  decision_intel: { velocity: string; velocity_note: string; decision_makers: DecisionMaker[] }
  actions: ActionItem[]
  messages: Message[]
  tl_directive: string
  suggested_client_reply: { drafted_for: string; to: string; body: string }
}

export const PID_DATA: Record<string, StaticPID> = {
  '24292': {
    pid:'24292', couple:'Aayushi · Dhruv',
    statusLevel:'attention', statusText:'ATTENTION · High-stakes execution · 7 days to event',
    risk_vectors:[{label:'Payment Risk',severity:'critical'},{label:'Bride Off-Channel',severity:'attention'},{label:'Open Commitments > 3',severity:'attention'},{label:'Vendor Advance Delay',severity:'attention'}],
    analysis:['Project is executing but under genuine pressure. <strong>Installment 2 of the negotiated payment plan is now overdue</strong> — ₹7.55L was due April 25/26, and as of April 27 EOD, Vendor Manager Bhavya was still asking about the transfer. Installment 1 (₹7.55L) was also paid 2 days late on April 23 after sustained follow-up. The pattern: client pays, but only after pressure. This is the dominant operational risk because <strong>decor advance releases are gated on collection</strong>.','The bride explicitly stated she would be <strong>unavailable from April 25 onward</strong>, meaning every approval decision in the final 10 days compressed into a narrow window that has now closed. Three live items still need sign-off: final itinerary board, updated room list, and guest ID matching.','Despite pressure indicators, sentiment from the couple remains <strong>cooperative and detail-engaged</strong> — not adversarial. <strong>Cancellation probability is low (~6%)</strong>; the real risks are operational slippage and the team carrying compounding stress through execution week.'],
    team_status:[{role:'Planner',name:'Bhavika Gurnani',initials:'BG',color:'#7241BE',bg:'rgba(114,65,190,0.15)',engagement:'Active',last_action:'Today, 12:31 PM',carrying_signal:'Stretched',notes:'Driving daily ops, payment chase, vendor coord — 236 messages in last 7d'},{role:'Designer',name:'Jaishree Patel',initials:'JP',color:'#EC4899',bg:'rgba(236,72,153,0.15)',engagement:'Steady',last_action:'2d ago',carrying_signal:'Steady',notes:'Printables and decor design on track.'},{role:'PM',name:'Anirudh Pathak',initials:'AP',color:'#14B8A6',bg:'rgba(20,184,166,0.15)',engagement:'Steady',last_action:'6 days ago',carrying_signal:'Steady',notes:'Vendor execution detail. Coverage looks complete.'},{role:'Designer (support)',name:'Pragya Awasthi',initials:'PA',color:'#EC4899',bg:'rgba(236,72,153,0.15)',engagement:'Active',last_action:'2d ago',carrying_signal:'Steady',notes:'Pulled in for itinerary board — pending bride approval'}],
    comms:{client_chattiness:87,client_chattiness_label:'High touch',last_client_message:'2d ago, 7:57 PM',off_channel_indicator:false,open_commitments:4,open_commitments_detail:['Bhavika: "I\'ll share the room list by today eod" (April 27, not closed)','Bhavika: "Will be done tonight" re payment escalation (April 22, partially closed)','Pragya: itinerary board upload by April 27 EOD (still awaiting bride approval)','Bhavika to Aayushi: "I\'ll check with finance team and get back" (April 23, not closed)']},
    vendor_coverage:[{vendor_type:'Decor',status:'confirmed',note:'Locked April 25, advance gated on Installment 2'},{vendor_type:'Photography (Shimla)',status:'confirmed',note:'Visuvam confirmed'},{vendor_type:'Photography (Delhi)',status:'confirmed',note:'Aligned April 21'},{vendor_type:'Catering',status:'in_progress',note:'60/meal vendor food rate to confirm with venue'},{vendor_type:'Floral',status:'confirmed',note:'Baby\'s breath + chamomile + waxflower mix locked'},{vendor_type:'Liquor',status:'in_progress',note:'Bride coordinating direct'},{vendor_type:'MUA',status:'in_progress',note:'Haldi MUA flowers TBD'},{vendor_type:'Choreography',status:'confirmed',note:'8 dance videos — finalized Feb'},{vendor_type:'Anchor',status:'confirmed',note:'Locked Feb'},{vendor_type:'Vintage Car',status:'confirmed',note:'Decor approved April 21'}],
    decision_intel:{velocity:'fast',velocity_note:'Aayushi decides within 24h on creative items; financial decisions go through Dhruv with 2-3 day lag',decision_makers:[{name:'Aayushi',role:'Bride',authority:'Execution & creative — drives all design, music, vendor specifics'},{name:'Dhruv',role:'Groom',authority:'Financial gate — all payment timing flows through him'},{name:'Bride\'s mother',role:'Family',authority:'Not in chat — likely consulted offline on family decisions'}]},
    actions:[{text:'Confirm Installment 2 (₹7.55L) status with Dhruv directly — overdue since April 25',priority:'critical'},{text:'Lock final itinerary board with Aayushi — open since April 27 EOD',priority:'critical'},{text:'Resolve 6-chair mandap reconfiguration — confirm Jaishree updated decor brief',priority:'critical'},{text:'Close out unmatched guest IDs with Abeer — venue access needs 48-72 hr notice',priority:'important'},{text:'Brief execution team for T-3 day decision crunch — bride will go non-responsive',priority:'important'},{text:'Confirm liquor delivery to The Manor on May 5, 12 PM',priority:'routine'}],
    messages:[{sender:'~ Aayushi',role:'Bride',initials:'AY',color:'#8B5CF6',bg:'rgba(139,92,246,0.15)',time:'6 days ago',body:'Meragi: liquor noc, 3 vehicles at property, vendor food 60/meal, runner briefing, room allot, Delhi photographer call, wedding saree drape, light effects during dances, baraat car and decor, fun facts 75, wedding area sweeped...',negative:false},{sender:'Amaan',role:'Team Lead (you)',initials:'AA',color:'#7241BE',bg:'rgba(114,65,190,0.15)',time:'6 days ago',body:'Yes, please let him know decor prep is getting delayed because of payment delay.',negative:true},{sender:'Meragi Bhavya',role:'Vendor Manager',initials:'MB',color:'#F59E0B',bg:'rgba(245,158,11,0.15)',time:'2d ago',body:'@Bhavika Meragi any update on 2nd installment',negative:true},{sender:'Pragya Awasthi',role:'Designer',initials:'PA',color:'#EC4899',bg:'rgba(236,72,153,0.15)',time:'2d ago, 5:17 PM',body:'Hey Bhavika, can you please share the final details for the itinerary board we need to upload by today eod on the drive',negative:false}],
    tl_directive:'Bhavika — three things to close today: (1) Direct call with Dhruv on Installment 2 (₹7.55L, due April 25/26, now 3 days overdue). (2) Final itinerary lock with Aayushi before further off-grid drift. (3) Confirm with Jaishree and Anirudh that the 6-chair mandap revision is reflected in the decor brief.',
    suggested_client_reply:{drafted_for:'Bhavika Gurnani',to:'Dhruv',body:'Hi Dhruv — hope you\'re doing well! Following up on the second installment of ₹7,55,000 that was scheduled for April 25/26 as per our agreed plan. Could you please confirm when this will be processed? We\'re lining up the final vendor advances and want to make sure decor prep stays on track for the 5th. — Bhavika'}
  },
  '20614': {
    pid:'20614', couple:'Kashish · Aditya', statusLevel:'attention', statusText:'ATTENTION · Escalated history · Monitor proactively',
    risk_vectors:[{label:'Escalated CX History',severity:'attention'},{label:'Low Collection (24%)',severity:'attention'}],
    analysis:['This project carries a legacy escalation risk that has been structurally resolved but must not be forgotten. In January 2026, the bride\'s mother (Madhur Dubey, based in London) <strong>sent a formal complaint message</strong> citing three planner changes, missed meetings, and no designer allocation for 11 months. Amaan personally intervened on January 10.','Current status is operationally healthy — venue fully bought out at Shiv Vilas Resort (200-250 guests). At 226 days out, <strong>₹5.68L has been collected of ₹23.35L SP (24.35%)</strong> — appropriate for this stage. The key risk is that the family has high expectations and low forgiveness: any future lapse will be treated as confirmation of prior concerns.'],
    team_status:[{role:'Planner',name:'Bhavika Gurnani',initials:'BG',color:'#7241BE',bg:'rgba(114,65,190,0.15)',engagement:'Active',last_action:'2 weeks ago',carrying_signal:'Stretched',notes:'Managing alongside 24292 (execution week) — stretched across both'},{role:'Designer',name:'Jaishree Patel',initials:'JP',color:'#EC4899',bg:'rgba(236,72,153,0.15)',engagement:'Steady',last_action:'2 weeks ago',carrying_signal:'Steady',notes:'Added Jan 14. Decor discussions deferred to Aug-Sep.'},{role:'Co-planner',name:'Bhavi (RJ)',initials:'BR',color:'#7241BE',bg:'rgba(114,65,190,0.15)',engagement:'Steady',last_action:'2 weeks ago',carrying_signal:'Steady',notes:'Venue POC, ongoing support'}],
    comms:{client_chattiness:45,client_chattiness_label:'Moderate',last_client_message:'2 weeks ago',off_channel_indicator:false,open_commitments:2,open_commitments_detail:['Bhavika: share full MOM from January 16 intro call (partially done)','Bhavi: share rooming, venue images, cost sheet from Mohit\'s handover']},
    vendor_coverage:[{vendor_type:'Venue',status:'confirmed',note:'Shiv Vilas Resort, full property buy-out, 110 rooms'},{vendor_type:'Catering',status:'confirmed',note:'In-house via Shiv Vilas Resort'},{vendor_type:'Decor',status:'unassigned',note:'Deferred to Aug-Sep 2026'},{vendor_type:'Sound License',status:'in_progress',note:'Required, sound till 2-3 AM'},{vendor_type:'Drone License',status:'in_progress',note:'Required'},{vendor_type:'Liquor License',status:'in_progress',note:'Required'}],
    decision_intel:{velocity:'moderate',velocity_note:'Bride\'s mother (Madhur Dubey) is the primary decision-maker and is based in London — synchronous calls needed',decision_makers:[{name:'Madhur Dubey',role:'Bride\'s mother',authority:'Primary POC for all planning decisions, based in London'},{name:'Kashish',role:'Bride',authority:'Final creative approval, based in Australia'},{name:'Aditya',role:'Groom',authority:'Co-decision on logistics, Jabalpur family'}]},
    actions:[{text:'Schedule next proactive check-in with Madhur Dubey — due within 2 weeks',priority:'important'},{text:'Complete and share full MOM from January 16 intro call',priority:'important'},{text:'Plan decor discussion timeline for Aug-Sep — set expectation now',priority:'routine'},{text:'Confirm rooming details (3-4 rooms still pending for Dec 12)',priority:'routine'}],
    messages:[{sender:'~ Madhur Dubey',role:'Bride\'s mother',initials:'MD',color:'#8B5CF6',bg:'rgba(139,92,246,0.15)',time:'Jan 10',body:'This was completely unacceptable — we travelled from London to discuss and iron out details but your team unavailability put everything to a grinding halt.',negative:true},{sender:'Amaan',role:'Team Lead (you)',initials:'AA',color:'#7241BE',bg:'rgba(114,65,190,0.15)',time:'Jan 10',body:'Hey Madhur, This is Amaan, the Jaipur Team\'s new Planning Lead. I want to start off apologising for the experience. Let me connect with you on Monday.',negative:false},{sender:'~ Madhur Dubey',role:'Bride\'s mother',initials:'MD',color:'#8B5CF6',bg:'rgba(139,92,246,0.15)',time:'Jan 13',body:'Thanks Amaan for the introductory call. Look forward to be connected with the team.',negative:false},{sender:'Bhavika Gurnani',role:'Planner',initials:'BG',color:'#7241BE',bg:'rgba(114,65,190,0.15)',time:'Jan 16',body:'Hello everyone, It was great speaking with you all. We\'ll get back to you with all the updates as discussed.',negative:false}],
    tl_directive:'Bhavika — the escalation is behind us but do not let this CX drift. Madhur Dubey is keeping score. Schedule a proactive check-in this week even if there is nothing urgent to discuss.',
    suggested_client_reply:{drafted_for:'Bhavika Gurnani',to:'Madhur Dubey',body:'Hi Madhur — hope you\'re both doing well! Wanted to check in and share a quick update: we\'re progressing well on the Shiv Vilas coordination. The rooming inventory is being finalized and we\'re blocking out August for the full decor planning sessions as discussed. — Bhavika'}
  },
  '24401': {
    pid:'24401', couple:'Shubhangi · Vinay', statusLevel:'attention', statusText:'ATTENTION · Low collection · Slow planning start',
    risk_vectors:[{label:'Low Collection (12.5%)',severity:'attention'},{label:'Slow Planning Start',severity:'attention'}],
    analysis:['This project has a slow start. The group was created in October 2025, but the planner (Tapasya) was only introduced on February 27, 2026 — <strong>over 4 months after booking</strong>. At ₹25,000 collected on a ₹2L SP (12.5%), collection velocity is below par. On April 2, the Vendor Manager Lead (Monu) flagged "just 25k collected as of now" directly to Amaan.','Positive signals: as of late April, Tapasya has shared DJ and anchor options and vendor discussion appears to be moving. The couple (Shubhangi and Vinay, Delhi-based) were communicative in Feb-Mar. The planning window is 210 days — adequate time to execute well if momentum builds now.'],
    team_status:[{role:'Planner',name:'Tapasya Waldia',initials:'TW',color:'#7241BE',bg:'rgba(114,65,190,0.15)',engagement:'Active',last_action:'1 week ago',carrying_signal:'Steady',notes:'Added Feb 27. First vendor options shared late April.'},{role:'Designer',name:'Somila Bhadauriya',initials:'SB',color:'#EC4899',bg:'rgba(236,72,153,0.15)',engagement:'Steady',last_action:'3 weeks ago',carrying_signal:'Steady',notes:'Added Mar 31. Design discussions not yet started.'},{role:'PM',name:'Nikhil Gupta',initials:'NG',color:'#14B8A6',bg:'rgba(20,184,166,0.15)',engagement:'Active',last_action:'1 week ago',carrying_signal:'Steady',notes:'Added April 20. DJ/anchor vendor options shared April 22.'}],
    comms:{client_chattiness:35,client_chattiness_label:'Low-moderate',last_client_message:'2 months ago',off_channel_indicator:false,open_commitments:2,open_commitments_detail:['Tapasya: connect with couple to discuss initial vendor preferences','Somila: share decor moodboards for initial direction']},
    vendor_coverage:[{vendor_type:'Venue',status:'confirmed',note:'Sunday Hotels and Resort, Gurgaon — booked Nov 24-25'},{vendor_type:'DJ',status:'in_progress',note:'Options shared: DJ Nikhil (25K), DJ Beatrix (40K)'},{vendor_type:'Anchor',status:'in_progress',note:'Options shared: Aishwarya (40K), Aiman (35K)'},{vendor_type:'Decor',status:'unassigned',note:'Not yet discussed — awaiting designer introduction call'},{vendor_type:'Photography',status:'unassigned',note:'Not yet discussed'}],
    decision_intel:{velocity:'moderate',velocity_note:'Couple is communicative but required follow-up; Vinay is primary POC on WhatsApp, Shubhangi handles logistics',decision_makers:[{name:'Vinay',role:'Groom',authority:'Primary WhatsApp contact, initiates follow-ups'},{name:'Shubhangi',role:'Bride',authority:'Logistics and vendor preferences, responds when pinged'}]},
    actions:[{text:'Schedule intro planning call with Shubhangi & Vinay — overdue',priority:'critical'},{text:'Push Somila to share decor moodboards — design discussion not yet started',priority:'important'},{text:'Follow up on DJ/anchor options shared April 22 — no response yet',priority:'important'},{text:'Address collection gap — align next installment date with couple',priority:'important'}],
    messages:[{sender:'~ Vinay Sehwag',role:'Groom',initials:'VS',color:'#8B5CF6',bg:'rgba(139,92,246,0.15)',time:'Feb 26',body:'Hi Ayush, as discussed previously can you please share some executed images of the Sunday Resort? And please schedule the planner call for some initial vendor references.',negative:false},{sender:'Tapasya Waldia',role:'Planner',initials:'TW',color:'#7241BE',bg:'rgba(114,65,190,0.15)',time:'Feb 27',body:'Hey Shubhangi & Vinay!! Heartiest congratulations to you both on your wedding!!! This is Tapasya, your planner!',negative:false},{sender:'Monu Meragi VM Lead',role:'VM Lead',initials:'MV',color:'#F59E0B',bg:'rgba(245,158,11,0.15)',time:'Apr 2',body:'@Amaan have we assigned any designer for this project? @Tapasya Any movement with this client — we have just collected 25k as of now?',negative:true}],
    tl_directive:'Tapasya — this project has been slow to start and the collection gap is now flagged by VM. Priority: (1) Get on a call with Shubhangi & Vinay this week. (2) Push Somila to initiate design discussions. (3) Follow up on DJ/anchor options.',
    suggested_client_reply:{drafted_for:'Tapasya Waldia',to:'Shubhangi & Vinay',body:'Hi Shubhangi & Vinay — hope you\'re both doing well! We\'ve now got the full team in place. Could we schedule a call this week to officially kick off the planning? — Tapasya'}
  },
  '25210': {
    pid:'25210', couple:'Vienna · Ishan', statusLevel:'attention', statusText:'ATTENTION · Near-zero collection · Early stage',
    risk_vectors:[{label:'Near-Zero Collection (0.8%)',severity:'attention'},{label:'Package Oversize vs GMV',severity:'attention'}],
    analysis:['Vienna and Ishan booked Bhairavgarh Palace in Udaipur for Oct 25-26. Only ₹25K has been collected (0.84%) — very low but the project was recently assigned to Bhavika\'s team. At 180 days out, the priority is establishing a solid planning cadence and a clear payment schedule.','The internal group was set up recently, and initial discussions are focused on venue layout and package scope. The couple appears engaged based on early message patterns. No red flags on relationship.'],
    team_status:[{role:'Planner',name:'Bhavika Gurnani',initials:'BG',color:'#7241BE',bg:'rgba(114,65,190,0.15)',engagement:'Steady',last_action:'1 week ago',carrying_signal:'Stretched',notes:'Managing alongside 24292 execution and 20614 — stretched'},{role:'Designer',name:'Shreyanshu Tiwari',initials:'ST',color:'#8B5CF6',bg:'rgba(139,92,246,0.15)',engagement:'Steady',last_action:'1 week ago',carrying_signal:'Steady',notes:'Initial venue layout discussions underway'},{role:'PM',name:'Varun Mittal',initials:'VM',color:'#14B8A6',bg:'rgba(20,184,166,0.15)',engagement:'Steady',last_action:'1 week ago',carrying_signal:'Steady',notes:'Recently assigned'}],
    comms:{client_chattiness:40,client_chattiness_label:'Low-moderate',last_client_message:'1 week ago',off_channel_indicator:false,open_commitments:1,open_commitments_detail:['Bhavika: share initial planning timeline and payment schedule']},
    vendor_coverage:[{vendor_type:'Venue',status:'confirmed',note:'Bhairavgarh Palace, Udaipur — Oct 25-26'},{vendor_type:'Decor',status:'unassigned',note:'Not yet discussed'},{vendor_type:'Photography',status:'unassigned',note:'Not yet discussed'}],
    decision_intel:{velocity:'moderate',velocity_note:'Couple seems to co-decide; scheduling takes 1-2 days',decision_makers:[{name:'Ishan',role:'Groom',authority:'Primary contact'},{name:'Vienna',role:'Bride',authority:'Design and vendor preferences'}]},
    actions:[{text:'Share initial planning timeline with Vienna & Ishan',priority:'important'},{text:'Formalize first installment schedule',priority:'important'},{text:'Initiate decor discussion once Shreyanshu has intro call',priority:'routine'}],
    messages:[{sender:'Bhavika Gurnani',role:'Planner',initials:'BG',color:'#7241BE',bg:'rgba(114,65,190,0.15)',time:'1 week ago',body:'Hi Vienna & Ishan — excited to be your planner for Bhairavgarh! Will share the planning timeline this week.',negative:false}],
    tl_directive:'Bhavika — get 25210 formally kicked off. A planning timeline and payment schedule confirmation will put this in a healthy position.',
    suggested_client_reply:{drafted_for:'Bhavika Gurnani',to:'Vienna & Ishan',body:'Hi Vienna & Ishan — sharing the planning timeline for your Bhairavgarh Palace wedding! Let\'s also align on the payment milestones. — Bhavika'}
  },
  '24202': {
    pid:'24202', couple:'Akshay · Nicole', statusLevel:'attention', statusText:'ATTENTION · Low collection · Early planning',
    risk_vectors:[{label:'Low Collection (6.25%)',severity:'attention'}],
    analysis:['Akshay & Nicole are booked at Fateh Garh in Udaipur for Nov 25-26. Aditya Sharma is the planner with Pragya Awasthi as designer and Narendra Singh as PM. The project is early stage with only 6.25% collected (₹25K of ₹4L SP).','Internal group shows team is in place and initial meetings have been scheduled. No significant risk signals detected in recent communications.'],
    team_status:[{role:'Planner',name:'Aditya Sharma',initials:'AS',color:'#F59E0B',bg:'rgba(245,158,11,0.15)',engagement:'Active',last_action:'1 week ago',carrying_signal:'Steady',notes:'Leading planning, venue coordination'},{role:'Designer',name:'Pragya Awasthi',initials:'PA',color:'#EC4899',bg:'rgba(236,72,153,0.15)',engagement:'Steady',last_action:'2 weeks ago',carrying_signal:'Steady',notes:'Design discussions being initiated'},{role:'PM',name:'Narendra Singh',initials:'NS',color:'#14B8A6',bg:'rgba(20,184,166,0.15)',engagement:'Steady',last_action:'2 weeks ago',carrying_signal:'Steady',notes:'Coordination support'}],
    comms:{client_chattiness:35,client_chattiness_label:'Low',last_client_message:'2 weeks ago',off_channel_indicator:false,open_commitments:1,open_commitments_detail:['Aditya: share planning timeline and initial vendor options']},
    vendor_coverage:[{vendor_type:'Venue',status:'confirmed',note:'Fateh Garh by Fateh Collection — Nov 25-26'},{vendor_type:'Decor',status:'unassigned',note:'Not yet discussed'},{vendor_type:'Photography',status:'unassigned',note:'Not yet discussed'}],
    decision_intel:{velocity:'moderate',velocity_note:'Akshay & Nicole — couple seems to co-decide; scheduling takes 1-2 days',decision_makers:[{name:'Akshay',role:'Groom',authority:'Primary planning contact'},{name:'Nicole',role:'Bride',authority:'Design and vendor preferences'}]},
    actions:[{text:'Schedule first formal planning call with Akshay & Nicole',priority:'important'},{text:'Formalize payment installment schedule',priority:'important'},{text:'Initiate decor moodboard with Pragya',priority:'routine'}],
    messages:[{sender:'Akshay · Nicole',role:'Client',initials:'AN',color:'#8B5CF6',bg:'rgba(139,92,246,0.15)',time:'2 weeks ago',body:'Hi Aditya — looking forward to connecting for the planning call!',negative:false}],
    tl_directive:'Aditya — get the payment schedule formalized for 24202 this month.',
    suggested_client_reply:{drafted_for:'Aditya Sharma',to:'Akshay & Nicole',body:'Hi Akshay & Nicole — excited to kick off planning for your Fateh Garh celebration! I\'ll be sharing the initial planning timeline and payment schedule this week. — Aditya'}
  },
  '30646': {
    pid:'30646', couple:'Chinmay · Jhanvi', statusLevel:'attention', statusText:'ATTENTION · 5% collection · Early but active',
    risk_vectors:[{label:'Low Collection (5%)',severity:'attention'},{label:'Pet request open',severity:'attention'}],
    analysis:['Chinmay & Jhanvi are booked at Sayaji Resort in Udaipur for Nov 20-21. Bhavika is the planner (added Feb 24) with the Udaipur team. Jhanvi asked about pet-friendly policy at Sayaji — the venue rep said no but promised to check again.','Only 5% collected (₹25K of ₹5L SP), but the project started in Feb 2026 and planning is actively moving forward. The couple\'s positive tone and quick responses suggest healthy relationship.'],
    team_status:[{role:'Planner',name:'Bhavika Gurnani',initials:'BG',color:'#7241BE',bg:'rgba(114,65,190,0.15)',engagement:'Active',last_action:'3 weeks ago',carrying_signal:'Stretched',notes:'Added Feb 24. Good rapport established with couple.'},{role:'Designer',name:'Shreyanshu Tiwari',initials:'ST',color:'#8B5CF6',bg:'rgba(139,92,246,0.15)',engagement:'Steady',last_action:'3 weeks ago',carrying_signal:'Steady',notes:'Initial decor discussion pending'},{role:'PM',name:'Varun Mittal',initials:'VM',color:'#14B8A6',bg:'rgba(20,184,166,0.15)',engagement:'Steady',last_action:'3 weeks ago',carrying_signal:'Steady',notes:'Venue coordination in progress'}],
    comms:{client_chattiness:50,client_chattiness_label:'Moderate',last_client_message:'3 weeks ago',off_channel_indicator:false,open_commitments:2,open_commitments_detail:['Abhishek (venue): recheck pet-friendly exception for Jhanvi\'s dog','Bhavika: follow up on planning timeline action items from March 9']},
    vendor_coverage:[{vendor_type:'Venue',status:'confirmed',note:'Sayaji Resort & Spa, Udaipur — Nov 20-21'},{vendor_type:'Decor',status:'unassigned',note:'Awaiting first design call with Shreyanshu'},{vendor_type:'Pet policy',status:'in_progress',note:'Venue rep checking — Jhanvi wants exception for her best friend\'s dog'}],
    decision_intel:{velocity:'moderate',velocity_note:'Jhanvi is primary creative contact; Chinmay handles logistics decisions',decision_makers:[{name:'Jhanvi',role:'Bride',authority:'Creative decisions, venue preferences, vendor approvals'},{name:'Chinmay',role:'Groom',authority:'Logistics and financial decisions'}]},
    actions:[{text:'Follow up on Sayaji pet policy for Jhanvi — pending since March 7',priority:'routine'},{text:'Schedule next planning touchpoint with couple',priority:'important'},{text:'Initiate decor moodboard sharing with Shreyanshu',priority:'routine'}],
    messages:[{sender:'~ Jhanvi',role:'Bride',initials:'JH',color:'#8B5CF6',bg:'rgba(139,92,246,0.15)',time:'Mar 7',body:'Is Sayaji Udaipur a pet friendly property? My best friend has a dog who is very dear to me, it would mean a lot if I can have her there.',negative:false},{sender:'Bhavika Gurnani',role:'Planner',initials:'BG',color:'#7241BE',bg:'rgba(114,65,190,0.15)',time:'Mar 9',body:'Hey Jhanvi & Chinmay — sharing the wedding timeline that we will be working with. Please have a look and let us know if any changes need to be made.',negative:false}],
    tl_directive:'Bhavika — close the pet policy loop with Sayaji (it\'s been 6 weeks), then schedule the next formal check-in. Don\'t lose momentum while you\'re in execution on 24292.',
    suggested_client_reply:{drafted_for:'Bhavika Gurnani',to:'Chinmay & Jhanvi',body:'Hi Chinmay & Jhanvi — checking in! We\'re progressing well on the Sayaji planning. Also wanted to update you on the pet question — I\'ve followed up with the venue and will share their final answer shortly. — Bhavika'}
  },
  '23671': {
    pid:'23671', couple:'Apoorv · Priya', statusLevel:'attention', statusText:'ATTENTION · Near-zero collection · Communication concerns',
    risk_vectors:[{label:'Near-Zero Collection (1.32%)',severity:'attention'},{label:'Early planner change',severity:'attention'}],
    analysis:['Apoorv & Priya are booked at Raga on the Ganges in Rishikesh for Nov 20-21. Despite being booked since March 2025, active planning only began in late Feb 2026 after a planner change. Only 1.32% collected (₹25K of ₹19L SP) — extremely low for a Nov wedding.','Priya requested weekday unavailability and Saturday calls. Urgency: collection and vendor locking must start in May.'],
    team_status:[{role:'Planner',name:'Tapasya Waldia',initials:'TW',color:'#7241BE',bg:'rgba(114,65,190,0.15)',engagement:'Active',last_action:'2 months ago',carrying_signal:'Steady',notes:'Took over Feb 26. Replaced previous planner.'},{role:'Designer',name:'Somila Bhadauriya',initials:'SB',color:'#EC4899',bg:'rgba(236,72,153,0.15)',engagement:'Active',last_action:'2 months ago',carrying_signal:'Steady',notes:'Moodboards shared Feb 25 — awaiting client feedback.'}],
    comms:{client_chattiness:30,client_chattiness_label:'Low',last_client_message:'2 months ago',off_channel_indicator:false,open_commitments:1,open_commitments_detail:['Priya: pending feedback on moodboards shared Feb 25 — no response yet']},
    vendor_coverage:[{vendor_type:'Venue',status:'confirmed',note:'Raga on the Ganges, Rishikesh — Nov 20-21'},{vendor_type:'Decor',status:'in_progress',note:'Moodboards shared Feb 25, awaiting feedback'}],
    decision_intel:{velocity:'deliberate',velocity_note:'Priya prefers weekends for calls, requires advance scheduling',decision_makers:[{name:'Priya',role:'Bride',authority:'Primary POC, design decisions'},{name:'Apoorv',role:'Groom',authority:'Logistics and budget'}]},
    actions:[{text:'Follow up on moodboard feedback from Priya — pending 2 months',priority:'critical'},{text:'Formalize payment installment schedule with Apoorv',priority:'critical'},{text:'Schedule weekend planning call for May',priority:'important'}],
    messages:[{sender:'~ Priya',role:'Bride',initials:'PR',color:'#8B5CF6',bg:'rgba(139,92,246,0.15)',time:'Feb 25',body:'Hi Somila, sorry missed replying earlier. Weekdays will be little difficult. If we aren\'t in a hurry, let\'s connect on the weekend, say Saturday around 3pm?',negative:false},{sender:'Tapasya Waldia',role:'Planner',initials:'TW',color:'#7241BE',bg:'rgba(114,65,190,0.15)',time:'Feb 26',body:'Hey Priya and Apoorv, I\'m Tapasya, your planner for the wedding. Really excited to get on this journey with you!',negative:false}],
    tl_directive:'Tapasya — no moodboard feedback in 2 months is a red flag on engagement. Schedule a Saturday call with Priya in early May to surface any concerns and re-engage. Also: the ₹19L SP with 1.32% collection needs a payment plan in the same call.',
    suggested_client_reply:{drafted_for:'Tapasya Waldia',to:'Priya & Apoorv',body:'Hi Priya & Apoorv — just checking in! Somila shared some beautiful moodboards in February — would love to hear your thoughts. We\'re keen to lock in a planning call to discuss vendor options and payment milestones. Would Saturday morning work? — Tapasya'}
  },
  '33487': {
    pid:'33487', couple:'Hemant · Jashan', statusLevel:'healthy', statusText:'HEALTHY · Strong start · Active couple',
    risk_vectors:[{label:'Low Collection (19%)',severity:'attention'}],
    analysis:['Hemant & Jashan are among the most recently booked PIDs but have shown exceptional early engagement. After team assignment on April 22, Jashan responded enthusiastically the same day. By April 24, Jaishree had shared venue images and Tapasya had shared the mastersheet link with full timeline and payment schedule.','By April 26, Hemant was already requesting decor execution images. This couple is fast-moving and high-engagement — the team needs to match the energy.'],
    team_status:[{role:'Planner',name:'Tapasya Waldia',initials:'TW',color:'#7241BE',bg:'rgba(114,65,190,0.15)',engagement:'Active',last_action:'3 days ago',carrying_signal:'Steady',notes:'Fast onboarding. Mastersheet shared April 24.'},{role:'Designer',name:'Jaishree Patel',initials:'JP',color:'#EC4899',bg:'rgba(236,72,153,0.15)',engagement:'Active',last_action:'2 days ago',carrying_signal:'Steady',notes:'Venue images shared April 24. Decor execution images sent April 26.'},{role:'PM',name:'Nikhil Gupta',initials:'NG',color:'#14B8A6',bg:'rgba(20,184,166,0.15)',engagement:'Steady',last_action:'1 week ago',carrying_signal:'Steady',notes:'Added to group'}],
    comms:{client_chattiness:75,client_chattiness_label:'High',last_client_message:'2 days ago',off_channel_indicator:false,open_commitments:1,open_commitments_detail:['Tapasya: share additional makeup artist profiles as discussed']},
    vendor_coverage:[{vendor_type:'Venue',status:'confirmed',note:'The Claridges, Mussoorie — Nov 20-21'},{vendor_type:'MUA',status:'in_progress',note:'Deepika Tiwari profile shared April 24 — awaiting couple feedback'},{vendor_type:'Decor',status:'in_progress',note:'Venue images shared; couple reviewing execution photos'}],
    decision_intel:{velocity:'fast',velocity_note:'Jashan drives decisions quickly; Hemant adds specifics on vendor aesthetics',decision_makers:[{name:'Jashan',role:'Bride',authority:'Primary POC, all planning decisions'},{name:'Hemant',role:'Groom',authority:'Vendor aesthetic feedback, secondary approvals'}]},
    actions:[{text:'Send 2-3 more makeup artist profiles as promised',priority:'important'},{text:'Schedule photography discussion — couple is fast-moving',priority:'routine'},{text:'Follow up on MUA feedback from Deepika Tiwari profile',priority:'routine'}],
    messages:[{sender:'~ Jashan',role:'Bride',initials:'JA',color:'#8B5CF6',bg:'rgba(139,92,246,0.15)',time:'Apr 23',body:'Hi guys, we\'ll be travelling back next week, and before that I\'d really like to finalize key vendors like makeup and photography. Could you guide us?',negative:false},{sender:'~ Hemant Nandra',role:'Groom',initials:'HN',color:'#8B5CF6',bg:'rgba(139,92,246,0.15)',time:'Apr 26',body:'Hi Jaishree — could you share the pictures & videos of the wedding decorations from April 19-20? We are expecting to see decoration pictures instead of the property.',negative:false}],
    tl_directive:'Tapasya & Jaishree — great start with Hemant & Jashan. Keep the momentum. Send the additional MUA profiles promised on April 24. This is your strongest new project.',
    suggested_client_reply:{drafted_for:'Tapasya Waldia',to:'Jashan & Hemant',body:'Hi Jashan & Hemant — sharing 3 more makeup artist profiles as promised! Let us know your thoughts and we can set up a quick call before you travel. — Tapasya'}
  },
  '28438': {
    pid:'28438', couple:'Dharmik · Suchi', statusLevel:'attention', statusText:'ATTENTION · Low collection · Early planning',
    risk_vectors:[{label:'Low Collection (6.25%)',severity:'attention'}],
    analysis:['Dharmik & Suchi are booked at Daulatgarh Resort in Udaipur for Nov 27-28. Only 6.25% collected on a ₹4L SP, and the event is 7 months out.','Team is in place with Shreyanshu (designer) and Varun (PM). Early planning communications suggest couple is engaged and responsive.'],
    team_status:[{role:'Planner',name:'Bhavika Gurnani',initials:'BG',color:'#7241BE',bg:'rgba(114,65,190,0.15)',engagement:'Steady',last_action:'3 weeks ago',carrying_signal:'Stretched',notes:'Managing alongside 24292 (execution) and 20614'},{role:'Designer',name:'Shreyanshu Tiwari',initials:'ST',color:'#8B5CF6',bg:'rgba(139,92,246,0.15)',engagement:'Steady',last_action:'3 weeks ago',carrying_signal:'Steady',notes:'Initial design call pending'},{role:'PM',name:'Varun Mittal',initials:'VM',color:'#14B8A6',bg:'rgba(20,184,166,0.15)',engagement:'Steady',last_action:'3 weeks ago',carrying_signal:'Steady',notes:'Venue coordination starting'}],
    comms:{client_chattiness:35,client_chattiness_label:'Low',last_client_message:'3 weeks ago',off_channel_indicator:false,open_commitments:1,open_commitments_detail:['Bhavika: schedule formal intro planning call']},
    vendor_coverage:[{vendor_type:'Venue',status:'confirmed',note:'Daulatgarh Resort, Udaipur — Nov 27-28'},{vendor_type:'Decor',status:'unassigned',note:'Not yet discussed'},{vendor_type:'Photography',status:'unassigned',note:'Not yet discussed'}],
    decision_intel:{velocity:'moderate',velocity_note:'Couple based in Delhi; typical 2-3 day response time',decision_makers:[{name:'Dharmik',role:'Groom',authority:'Primary contact'},{name:'Suchi',role:'Bride',authority:'Design and vendor decisions'}]},
    actions:[{text:'Schedule formal intro planning call with Dharmik & Suchi',priority:'important'},{text:'Establish next installment timeline in writing',priority:'important'},{text:'Initiate decor moodboard with Shreyanshu',priority:'routine'}],
    messages:[{sender:'Bhavika Gurnani',role:'Planner',initials:'BG',color:'#7241BE',bg:'rgba(114,65,190,0.15)',time:'3 weeks ago',body:'Hi Dharmik & Suchi — excited to be your planner for your Daulatgarh celebration! Will share the planning timeline this week.',negative:false}],
    tl_directive:'Bhavika — get 28438 formally kicked off. A quick 30-min call with Dharmik & Suchi and a payment schedule confirmation will put this in a healthy position.',
    suggested_client_reply:{drafted_for:'Bhavika Gurnani',to:'Dharmik & Suchi',body:'Hi Dharmik & Suchi — time to officially kick off your Daulatgarh planning! I\'d love to schedule a call this week to walk through the full planning timeline. — Bhavika'}
  },
  '31341': {
    pid:'31341', couple:'Vishakha · Utkarsh', statusLevel:'healthy', statusText:'HEALTHY · On track · Active planning',
    risk_vectors:[{label:'Low Collection (12.5%)',severity:'attention'}],
    analysis:['Vishakha & Utkarsh are booked at Shree Jee Vilas in Sonepat for Dec 4-5. The internal group shows active planning in progress with Tapasya\'s team. At 12.5% collection on ₹2L SP, the project is on a healthy trajectory for a 7-month-out event.','The couple appears engaged and the planning cadence is active based on recent messages.'],
    team_status:[{role:'Planner',name:'Tapasya Waldia',initials:'TW',color:'#7241BE',bg:'rgba(114,65,190,0.15)',engagement:'Active',last_action:'2 weeks ago',carrying_signal:'Steady',notes:'Active planning underway'},{role:'Designer',name:'Somila Bhadauriya',initials:'SB',color:'#EC4899',bg:'rgba(236,72,153,0.15)',engagement:'Steady',last_action:'2 weeks ago',carrying_signal:'Steady',notes:'Design discussions in progress'},{role:'PM',name:'Nikhil Gupta',initials:'NG',color:'#14B8A6',bg:'rgba(20,184,166,0.15)',engagement:'Steady',last_action:'2 weeks ago',carrying_signal:'Steady',notes:'Coordination ongoing'}],
    comms:{client_chattiness:45,client_chattiness_label:'Moderate',last_client_message:'2 weeks ago',off_channel_indicator:false,open_commitments:1,open_commitments_detail:['Somila: share updated decor moodboards']},
    vendor_coverage:[{vendor_type:'Venue',status:'confirmed',note:'Shree Jee Vilas, Sonepat — Dec 4-5'},{vendor_type:'Decor',status:'in_progress',note:'Moodboards in progress with Somila'}],
    decision_intel:{velocity:'moderate',velocity_note:'Vishakha is primary POC; Utkarsh handles logistics',decision_makers:[{name:'Vishakha',role:'Bride',authority:'Design and vendor decisions'},{name:'Utkarsh',role:'Groom',authority:'Budget and logistics'}]},
    actions:[{text:'Share updated decor moodboards from Somila',priority:'routine'},{text:'Schedule next planning check-in',priority:'routine'},{text:'Align on next installment date',priority:'routine'}],
    messages:[{sender:'Vishakha · Utkarsh',role:'Client',initials:'VU',color:'#8B5CF6',bg:'rgba(139,92,246,0.15)',time:'2 weeks ago',body:'Hi Tapasya — the moodboards look great! Can you share the updated version with the revisions we discussed?',negative:false}],
    tl_directive:'Tapasya — 31341 is in good shape. Keep the planning cadence going and align on the next installment date this month.',
    suggested_client_reply:{drafted_for:'Tapasya Waldia',to:'Vishakha & Utkarsh',body:'Hi Vishakha & Utkarsh — sharing the updated moodboards with all the revisions! Would love to get your feedback and then move to vendor locking discussions. — Tapasya'}
  },
  '32245': {
    pid:'32245', couple:'Pavan · Sheenam', statusLevel:'attention', statusText:'ATTENTION · Zero collection · Venue still under discussion',
    risk_vectors:[{label:'Zero Collection',severity:'attention'},{label:'Venue Not Yet Confirmed',severity:'attention'}],
    analysis:['Pavan & Sheenam have zero collection. As of late March/early April, the couple was doing venue recce between Kanooja Palace and Turban Bhawani Heritage. The choice is the current open item.','A site visit occurred on March 31. The decision between Kanooja (₹28L for 2-night buyout) and Turban Bhawani (₹14.5L for 50 rooms) is still pending.'],
    team_status:[{role:'Planner',name:'Aditya Sharma',initials:'AS',color:'#F59E0B',bg:'rgba(245,158,11,0.15)',engagement:'Active',last_action:'3 weeks ago',carrying_signal:'Steady',notes:'Venue recce organized and executed in late March'},{role:'Designer',name:'Jaishree Patel',initials:'JP',color:'#EC4899',bg:'rgba(236,72,153,0.15)',engagement:'Steady',last_action:'3 weeks ago',carrying_signal:'Steady',notes:'Design discussions pending venue finalization'}],
    comms:{client_chattiness:50,client_chattiness_label:'Moderate',last_client_message:'3 weeks ago',off_channel_indicator:false,open_commitments:2,open_commitments_detail:['Couple: decision between Kanooja Palace and Turban Bhawani — pending since April 1 recce','Aditya: follow up post-recce to nudge decision']},
    vendor_coverage:[{vendor_type:'Venue',status:'in_progress',note:'Decision pending between Kanooja Palace (₹28L) and Turban Bhawani (₹14.5L)'},{vendor_type:'Decor',status:'unassigned',note:'Awaiting venue selection'}],
    decision_intel:{velocity:'deliberate',velocity_note:'Family-driven decision; Pavan and Priyanka (family) are jointly deciding on venue',decision_makers:[{name:'Pavan',role:'Groom',authority:'Primary contact, logistics'},{name:'Sheenam',role:'Bride',authority:'Creative and vendor preferences'},{name:'Priyanka',role:'Family',authority:'Part of venue decision committee'}]},
    actions:[{text:'Follow up on venue decision — recce was March 31, no confirmation yet',priority:'critical'},{text:'Get first installment confirmation once venue is locked',priority:'important'},{text:'Once venue confirmed, initiate decor moodboard urgently',priority:'routine'}],
    messages:[{sender:'Aditya Sharma',role:'Planner',initials:'AS',color:'#F59E0B',bg:'rgba(245,158,11,0.15)',time:'Apr 1',body:'Follow up post-recce: how did the visit go? Both properties were very impressed with the wedding vision you shared!',negative:false}],
    tl_directive:'Aditya — the venue decision is now 3+ weeks overdue post-recce. Call Pavan directly this week and get a decision or a firm date for the decision. Zero collection at this stage for a Dec wedding is a risk.',
    suggested_client_reply:{drafted_for:'Aditya Sharma',to:'Pavan & Sheenam',body:'Hi Pavan & Sheenam — checking in on the venue decision post your Udaipur visit. We\'d love to get things moving for the Dec 10 wedding. Could we get on a quick call this week to finalize the venue and map out next steps? — Aditya'}
  },
  '19935': {
    pid:'19935', couple:'Rishab · Keerthana', statusLevel:'attention', statusText:'ATTENTION · Low collection · Active planning underway',
    risk_vectors:[{label:'Low Collection (10.9%)',severity:'attention'},{label:'No Designer or PM Assigned',severity:'critical'}],
    analysis:['Rishab & Keerthana are booked at Ramada Wyndham Kochi for Dec 12-14 (3 days). Ananth Santhosh is the planner with <strong>no designer or PM assigned</strong> — a critical Team 4 coverage gap. ₹99K collected of ₹9.07L SP.','Keerthana\'s family is engaged with multiple family members in the group. Planning appears to be moving on the venue side but design and execution planning has no resource assigned.'],
    team_status:[{role:'Planner',name:'Ananth Santhosh',initials:'AN',color:'#7241BE',bg:'rgba(114,65,190,0.15)',engagement:'Active',last_action:'2 weeks ago',carrying_signal:'Steady',notes:'Active planning. Managed intro call Feb 25.'},{role:'Designer',name:'.',initials:'?',color:'#F59E0B',bg:'rgba(245,158,11,0.10)',engagement:'Quiet',last_action:'.',carrying_signal:'Steady',notes:'UNASSIGNED — no designer allocated for this PID'},{role:'PM',name:'.',initials:'?',color:'#F59E0B',bg:'rgba(245,158,11,0.10)',engagement:'Quiet',last_action:'.',carrying_signal:'Steady',notes:'UNASSIGNED — no PM allocated for this PID'}],
    comms:{client_chattiness:55,client_chattiness_label:'Moderate',last_client_message:'2 weeks ago',off_channel_indicator:false,open_commitments:2,open_commitments_detail:['Ananth: schedule next planning call with Keerthana & Rishabh','Assign designer and PM urgently — 7 months out with 3-day event']},
    vendor_coverage:[{vendor_type:'Venue',status:'confirmed',note:'Ramada Wyndham Kochi — Chakola confirmed Dec 12, 2026'},{vendor_type:'Decor',status:'unassigned',note:'No designer assigned — critical gap for 3-day event'}],
    decision_intel:{velocity:'moderate',velocity_note:'Keerthana drives decisions; family has multiple stakeholders (Kala Anand, Rekha Sudhir)',decision_makers:[{name:'Keerthana',role:'Bride',authority:'Primary POC, planning decisions'},{name:'Rishabh',role:'Groom',authority:'Co-decision maker'},{name:'Kala Anand',role:'Family',authority:'Family coordination'}]},
    actions:[{text:'URGENT: Assign designer and PM for 19935 — 3-day Kerala wedding needs full team',priority:'critical'},{text:'Schedule planning call with Keerthana & Rishabh for May',priority:'important'},{text:'Initiate decor discussion once designer assigned',priority:'important'}],
    messages:[{sender:'~ Keerthana Anand',role:'Bride',initials:'KA',color:'#8B5CF6',bg:'rgba(139,92,246,0.15)',time:'Feb 12',body:'Hi, time to get the ball rolling on planning this! Are you available on Sundays?',negative:false},{sender:'Ananth Santhosh',role:'Planner',initials:'AN',color:'#7241BE',bg:'rgba(114,65,190,0.15)',time:'Feb 21',body:'Hello! This is Ananth, I\'ll be planning here with Amaan. Congratulations to the couple! Super excited to be a part of the team.',negative:false}],
    tl_directive:'Ananth — 19935 is a 3-day Kerala wedding (₹25L GMV) with no designer or PM. This is the most urgent Team 4 coverage gap. Raise this with Amaan for immediate assignment.',
    suggested_client_reply:{drafted_for:'Ananth Santhosh',to:'Keerthana & Rishabh',body:'Hi Keerthana & Rishabh — great news: venue is confirmed at Ramada Kochi for Dec 12-14. We\'re also completing our full planning team. Would love to schedule a call this week to walk through the complete planning roadmap. — Ananth'}
  },
  '28166': {
    pid:'28166', couple:'Yash · Anuka', statusLevel:'attention', statusText:'ATTENTION · Zero collection · Early stage',
    risk_vectors:[{label:'Zero Collection',severity:'attention'},{label:'Early Stage, Dec 2026',severity:'attention'}],
    analysis:['Yash & Anuka are booked at Fateh Garh in Udaipur for Dec 18-19. Zero collection on ₹2.5L SP — very early stage but the Dec date means planning needs to begin in earnest.','The client group shows limited messages — this is an early project with minimal engagement yet.'],
    team_status:[{role:'Planner',name:'Tapasya Waldia',initials:'TW',color:'#7241BE',bg:'rgba(114,65,190,0.15)',engagement:'Steady',last_action:'1 month ago',carrying_signal:'Steady',notes:'Team assigned, formal kickoff pending'},{role:'Designer',name:'Somila Bhadauriya',initials:'SB',color:'#EC4899',bg:'rgba(236,72,153,0.15)',engagement:'Quiet',last_action:'1 month ago',carrying_signal:'Steady',notes:'Design discussions not yet started'},{role:'PM',name:'Nikhil Gupta',initials:'NG',color:'#14B8A6',bg:'rgba(20,184,166,0.15)',engagement:'Quiet',last_action:'1 month ago',carrying_signal:'Steady',notes:'Recently assigned'}],
    comms:{client_chattiness:20,client_chattiness_label:'Very low',last_client_message:'1 month ago',off_channel_indicator:false,open_commitments:1,open_commitments_detail:['Tapasya: schedule formal intro planning call with Yash & Anuka']},
    vendor_coverage:[{vendor_type:'Venue',status:'confirmed',note:'Fateh Garh by Fateh Collection, Udaipur — Dec 18-19'},{vendor_type:'Decor',status:'unassigned',note:'Not yet discussed'},{vendor_type:'Photography',status:'unassigned',note:'Not yet discussed'}],
    decision_intel:{velocity:'unknown',velocity_note:'Very early stage — not enough interaction to assess velocity',decision_makers:[{name:'Anuka',role:'Bride',authority:'Planning POC'},{name:'Yash',role:'Groom',authority:'Co-decision maker'}]},
    actions:[{text:'Schedule formal intro call with Yash & Anuka this week',priority:'critical'},{text:'Collect first installment — zero payment is a risk indicator',priority:'critical'},{text:'Initiate decor moodboard from Somila',priority:'important'}],
    messages:[{sender:'Tapasya Waldia',role:'Planner',initials:'TW',color:'#7241BE',bg:'rgba(114,65,190,0.15)',time:'1 month ago',body:'Hi Yash & Anuka — excited to be your planner for your Fateh Garh celebration! Will share the planning timeline soon.',negative:false}],
    tl_directive:'Tapasya — 28166 has zero engagement and zero collection. A Dec 2026 wedding needs to start planning in May. Schedule the kickoff call this week.',
    suggested_client_reply:{drafted_for:'Tapasya Waldia',to:'Yash & Anuka',body:'Hi Yash & Anuka — so excited for your Fateh Garh wedding in December! We\'ve got the full team in place and are ready to kick things off. Could we schedule a call this week? — Tapasya'}
  },
  '32125': {
    pid:'32125', couple:'Khushali · Sapan', statusLevel:'attention', statusText:'ATTENTION · Premium GMV · Low collection · Handover in progress',
    risk_vectors:[{label:'Low Collection (6.25%)',severity:'attention'},{label:'₹67L GMV — highest in portfolio',severity:'attention'}],
    analysis:['Khushali & Sapan represent the <strong>highest GMV project in the portfolio at ₹67L</strong>, booked at ITC Mementos Ekaaya in Udaipur for Dec 19-21 (3 days). The team was assigned on March 23 after a formal handover call. With only 6.25% collected, planning is in early stages.','The ₹67L GMV at a luxury venue requires the most intensive planning treatment in Team 2. <strong>No PM assigned yet</strong> — a critical gap for a 3-day event at this scale.'],
    team_status:[{role:'Planner',name:'Aditya Sharma',initials:'AS',color:'#F59E0B',bg:'rgba(245,158,11,0.15)',engagement:'Active',last_action:'3 weeks ago',carrying_signal:'Steady',notes:'Handover call with Abhishek done March 24. Internal group active.'},{role:'Designer',name:'Somila Bhadauriya',initials:'SB',color:'#EC4899',bg:'rgba(236,72,153,0.15)',engagement:'Active',last_action:'3 weeks ago',carrying_signal:'Steady',notes:'Initial decor discussions starting. 79-page curated pitch already created by sales team.'},{role:'PM',name:'.',initials:'?',color:'#F59E0B',bg:'rgba(245,158,11,0.10)',engagement:'Quiet',last_action:'.',carrying_signal:'Steady',notes:'UNASSIGNED — ₹67L GMV requires PM urgently'}],
    comms:{client_chattiness:30,client_chattiness_label:'Low-moderate',last_client_message:'3 weeks ago',off_channel_indicator:false,open_commitments:2,open_commitments_detail:['Aditya: schedule first formal planning call with Khushali & Sapan','Assign PM urgently — 3-day ITC Mementos event needs dedicated execution support']},
    vendor_coverage:[{vendor_type:'Venue',status:'confirmed',note:'ITC Mementos Ekaaya, Udaipur — Dec 19-21 (3 days)'},{vendor_type:'Decor',status:'in_progress',note:'79-page curated proposal already shared by sales. Design discussions ongoing.'}],
    decision_intel:{velocity:'moderate',velocity_note:'High-value family — expect multiple decision makers',decision_makers:[{name:'Khushali',role:'Bride',authority:'Creative decisions'},{name:'Sapan',role:'Groom',authority:'Budget and logistics'}]},
    actions:[{text:'URGENT: Assign PM for 32125 — ₹67L ITC Mementos event requires full team',priority:'critical'},{text:'Schedule formal planning call with Khushali & Sapan',priority:'important'},{text:'Begin decor discussions based on 79-page curated pitch',priority:'important'}],
    messages:[{sender:'Amaan',role:'Team Lead (you)',initials:'AA',color:'#7241BE',bg:'rgba(114,65,190,0.15)',time:'Mar 23',body:'Added Aditya as the planner and Somila as the designer here. Selya will also be supporting Aditya in planning.',negative:false},{sender:'Aditya Sharma',role:'Planner',initials:'AS',color:'#F59E0B',bg:'rgba(245,158,11,0.15)',time:'Mar 24',body:'We had the handover call. Event details: 3 days Dec 19-21, ITC Mementos Udaipur. Couple has strong inspiration references from the curated pitch.',negative:false}],
    tl_directive:'Aditya — 32125 is your most important project by GMV. A 3-day ITC Mementos event needs a PM immediately. Formally kick off with Khushali & Sapan in May and leverage the 79-page curated pitch as the design launchpad.',
    suggested_client_reply:{drafted_for:'Aditya Sharma',to:'Khushali & Sapan',body:'Hi Khushali & Sapan — wonderful to connect! We\'re so excited for your ITC Mementos celebration. Somila has some beautiful design directions to share. Could we schedule a call this week? — Aditya'}
  },
  '33798': {
    pid:'33798', couple:'Rhusha · Arjun', statusLevel:'healthy', statusText:'HEALTHY · 9 months out · Early onboarding',
    risk_vectors:[{label:'Zero Collection',severity:'attention'}],
    analysis:['Rhusha & Arjun are booked at Mundota Fort & Palace in Rajasthan for Jan 5-6, 2027. Tapasya is the planner with Jaishree as designer and Nikhil as PM. The internal group was recently created with minimal activity.','Zero collection on ₹3L SP — expected for this stage. The key priority is establishing the planning relationship and first formal call.'],
    team_status:[{role:'Planner',name:'Tapasya Waldia',initials:'TW',color:'#7241BE',bg:'rgba(114,65,190,0.15)',engagement:'Steady',last_action:'.',carrying_signal:'Steady',notes:'Recently assigned'},{role:'Designer',name:'Jaishree Patel',initials:'JP',color:'#EC4899',bg:'rgba(236,72,153,0.15)',engagement:'Quiet',last_action:'.',carrying_signal:'Steady',notes:'Recently assigned'},{role:'PM',name:'Nikhil Gupta',initials:'NG',color:'#14B8A6',bg:'rgba(20,184,166,0.15)',engagement:'Quiet',last_action:'.',carrying_signal:'Steady',notes:'Recently assigned'}],
    comms:{client_chattiness:15,client_chattiness_label:'Minimal',last_client_message:'Recently added',off_channel_indicator:false,open_commitments:1,open_commitments_detail:['Tapasya: schedule introductory planning call']},
    vendor_coverage:[{vendor_type:'Venue',status:'confirmed',note:'Mundota Fort & Palace, Rajasthan — Jan 5-6, 2027'}],
    decision_intel:{velocity:'unknown',velocity_note:'Very early stage',decision_makers:[{name:'Rhusha',role:'Bride',authority:'Primary POC'},{name:'Arjun',role:'Groom',authority:'Co-decision maker'}]},
    actions:[{text:'Schedule introductory planning call with Rhusha & Arjun',priority:'routine'},{text:'Collect first installment — initiate payment discussion',priority:'routine'}],
    messages:[{sender:'Tapasya Waldia',role:'Planner',initials:'TW',color:'#7241BE',bg:'rgba(114,65,190,0.15)',time:'Recently',body:'Hi Rhusha & Arjun — congratulations on your upcoming wedding at Mundota Fort! Really excited to be your planner.',negative:false}],
    tl_directive:'Tapasya — 33798 is 9 months out and healthy. Schedule the intro call when your bandwidth allows — after the 33487 momentum is established.',
    suggested_client_reply:{drafted_for:'Tapasya Waldia',to:'Rhusha & Arjun',body:'Hi Rhusha & Arjun — so excited to start this journey with you for your beautiful Mundota Fort wedding! Could we schedule a call to do a proper introduction and discuss the initial planning milestones? — Tapasya'}
  },
  '26903': {
    pid:'26903', couple:'Radhika · Manan', statusLevel:'attention', statusText:'ATTENTION · Communication complaints · Handover needed',
    risk_vectors:[{label:'Communication Complaints',severity:'attention'},{label:'Missed Meeting',severity:'attention'},{label:'Low Collection (7.14%)',severity:'attention'}],
    analysis:['Radhika & Manan are booked at Sterling Aravalli in Udaipur for Feb 2-3, 2027. The project has a documented communication breakdown: on Feb 25, Aditya (newly introduced planner) missed the scheduled 9:30 AM intro call — Manan waited 15 minutes and both he and Radhika followed up. By Feb 28, Radhika sent a pointed message: <strong>"We were pushed to make payments to both Meragi and the property, and now we haven\'t seen any visible progress."</strong>','Aditya quickly reached out, aligning a Monday 9:30 AM call on March 3. Early recovery seems underway. Only 7.14% collected (₹25K of ₹3.5L SP).'],
    team_status:[{role:'Planner',name:'Aditya Sharma',initials:'AS',color:'#F59E0B',bg:'rgba(245,158,11,0.15)',engagement:'Active',last_action:'2 months ago',carrying_signal:'Steady',notes:'Introduced Feb 28. Missed first scheduled call. Recovery meeting aligned for March 3.'},{role:'Designer',name:'Jaishree Patel',initials:'JP',color:'#EC4899',bg:'rgba(236,72,153,0.15)',engagement:'Quiet',last_action:'2 months ago',carrying_signal:'Steady',notes:'Recently added, design discussions not yet started'}],
    comms:{client_chattiness:40,client_chattiness_label:'Low-moderate',last_client_message:'2 months ago',off_channel_indicator:false,open_commitments:2,open_commitments_detail:['Aditya: schedule proactive check-in post March 3 call','Share planning deliverables that demonstrate visible progress to couple']},
    vendor_coverage:[{vendor_type:'Venue',status:'confirmed',note:'Sterling Aravalli, Udaipur — Feb 2-3, 2027'},{vendor_type:'Decor',status:'unassigned',note:'Not yet discussed'}],
    decision_intel:{velocity:'moderate',velocity_note:'Manan handles scheduling; Radhika is detail-oriented and expects structured communication',decision_makers:[{name:'Radhika',role:'Bride',authority:'Primary POC, holds team accountable for communication'},{name:'Manan',role:'Groom',authority:'Scheduling and logistics'}]},
    actions:[{text:'Schedule proactive May check-in with Radhika & Manan',priority:'critical'},{text:'Share concrete planning deliverables — they\'ve flagged lack of visible progress',priority:'important'},{text:'Begin decor moodboard discussion with Jaishree',priority:'routine'}],
    messages:[{sender:'~ Radhika Thakkar',role:'Bride',initials:'RT',color:'#8B5CF6',bg:'rgba(139,92,246,0.15)',time:'Feb 28',body:'We are still waiting to hear from you regarding next steps. We were pushed to make payments to both Meragi and the property, and now that those are completed, we haven\'t seen any visible progress.',negative:true},{sender:'Aditya Sharma',role:'Planner',initials:'AS',color:'#F59E0B',bg:'rgba(245,158,11,0.15)',time:'Feb 28',body:'Hello Manan & Radhika — Aditya this side from Meragi. I\'ll be the planner for your wedding. I\'m sorry for the communication gap. Looking forward to connecting on Monday.',negative:false}],
    tl_directive:'Aditya — 26903 had a rough start and the couple has explicitly called out lack of progress. Your May check-in cannot be generic — bring a planning timeline, a list of vendor options, and concrete next milestones. Radhika is keeping score.',
    suggested_client_reply:{drafted_for:'Aditya Sharma',to:'Radhika & Manan',body:'Hi Radhika & Manan — hope you\'re both doing well! I wanted to share a planning update as we head into May. We\'ve been working on your Sterling Aravalli timeline and have some exciting vendor options to share. Could we schedule a call this week? — Aditya'}
  },
  '28172': {
    pid:'28172', couple:'Navya · Ashmann', statusLevel:'healthy', statusText:'HEALTHY · High-engagement family · Active planning',
    risk_vectors:[{label:'No Designer or PM Assigned',severity:'critical'},{label:'Large Family Group',severity:'attention'}],
    analysis:['Navya & Ashmann\'s wedding at The Leela Kovalam (Feb 20-22, 2027) is one of the most complex in the portfolio — a 4-day event with 6+ ceremony events, 300+ guests, and a GMV of ₹43.5L. Ananth Santhosh is the planner with Amaan personally involved. Intro call completed Feb 14.','Amit Syngle (bride\'s father) raised pointed questions on Feb 15 about team structure and on-ground manpower. <strong>No designer or PM assigned</strong> — critical gap for a ₹43.5L event. This is an internationally based couple with a sophisticated expectation profile.'],
    team_status:[{role:'Planner',name:'Ananth Santhosh',initials:'AN',color:'#7241BE',bg:'rgba(114,65,190,0.15)',engagement:'Active',last_action:'2 months ago',carrying_signal:'Steady',notes:'Driving planning. Amaan personally involved. Manpower structure shared Feb 15.'},{role:'Designer',name:'.',initials:'?',color:'#F59E0B',bg:'rgba(245,158,11,0.10)',engagement:'Quiet',last_action:'.',carrying_signal:'Steady',notes:'UNASSIGNED — ₹43.5L event requires designer immediately'},{role:'PM',name:'.',initials:'?',color:'#F59E0B',bg:'rgba(245,158,11,0.10)',engagement:'Quiet',last_action:'.',carrying_signal:'Steady',notes:'UNASSIGNED — 4-day event needs dedicated PM'}],
    comms:{client_chattiness:65,client_chattiness_label:'High',last_client_message:'2 months ago',off_channel_indicator:false,open_commitments:2,open_commitments_detail:['Ananth: confirm team composition for Leela Kovalam event specifics','Assign designer and PM — family is tracking team structure']},
    vendor_coverage:[{vendor_type:'Venue',status:'confirmed',note:'The Leela Kovalam — Feb 20-22, 2027'},{vendor_type:'Photography',status:'in_progress',note:'Discussed on intro call — shortlisting in progress'},{vendor_type:'Decor',status:'unassigned',note:'No designer — critical gap'}],
    decision_intel:{velocity:'deliberate',velocity_note:'Multi-family stakeholder group; Amit Syngle leads financial decisions; Navya on creative',decision_makers:[{name:'Navya',role:'Bride',authority:'Creative and vendor preferences, US-based'},{name:'Ashmann',role:'Groom',authority:'Co-decision, NRI'},{name:'Amit Syngle',role:'Family',authority:'Financial decisions, team structure validation'}]},
    actions:[{text:'URGENT: Assign designer and PM — ₹43.5L Leela Kovalam event, family tracking',priority:'critical'},{text:'Schedule next planning call with full family group',priority:'important'},{text:'Begin photography shortlisting as discussed',priority:'important'}],
    messages:[{sender:'~ Amit Syngle',role:'Bride\'s father',initials:'AM',color:'#8B5CF6',bg:'rgba(139,92,246,0.15)',time:'Feb 15',body:'You have quoted 2-4 lacs as your fee. Could you clarify approximately the number of people on ground and dedicated for the event? This is the most important info to know for a wedding of 300 guests.',negative:false},{sender:'Ananth Santhosh',role:'Planner',initials:'AN',color:'#7241BE',bg:'rgba(114,65,190,0.15)',time:'Feb 15',body:'At our previous event at Novotel, the team was: Planning Lead 1, Planner 1, Co-Planner 1, Runners 4. For your event, we would scale this to match the 4-day scope and 6+ ceremony events.',negative:false}],
    tl_directive:'Ananth — 28172 is your most important project. ₹43.5L at The Leela Kovalam with no designer or PM is a serious gap and the family is watching. Escalate resource needs to me immediately.',
    suggested_client_reply:{drafted_for:'Ananth Santhosh',to:'Navya & Ashmann\'s family',body:'Hi everyone — hope you\'re all well! Wanted to share an update: we\'re finalizing the complete planning and design team for your Leela Kovalam wedding. We\'ll have the full team structure confirmed by next week. Could we schedule a call to discuss the planning roadmap and photography shortlist? — Ananth'}
  },
  '29568': {
    pid:'29568', couple:'Akhil · Poorvi', statusLevel:'healthy', statusText:'HEALTHY · 10 months out · Early stage',
    risk_vectors:[],
    analysis:['Akhil & Poorvi are booked at Wyndham Garden in Udaipur for Feb 23-24, 2027. Aditya Sharma is the planner with Jaishree Patel as designer. At 10 months out with 12.5% collection, this project is in healthy early-stage territory.','The internal group shows the team is assigned and active. No risk signals at this stage.'],
    team_status:[{role:'Planner',name:'Aditya Sharma',initials:'AS',color:'#F59E0B',bg:'rgba(245,158,11,0.15)',engagement:'Steady',last_action:'3 weeks ago',carrying_signal:'Steady',notes:'Team assigned and active'},{role:'Designer',name:'Jaishree Patel',initials:'JP',color:'#EC4899',bg:'rgba(236,72,153,0.15)',engagement:'Steady',last_action:'3 weeks ago',carrying_signal:'Steady',notes:'Initial discussions pending'}],
    comms:{client_chattiness:30,client_chattiness_label:'Low',last_client_message:'3 weeks ago',off_channel_indicator:false,open_commitments:1,open_commitments_detail:['Aditya: schedule first formal planning call']},
    vendor_coverage:[{vendor_type:'Venue',status:'confirmed',note:'Wyndham Garden, Udaipur — Feb 23-24, 2027'}],
    decision_intel:{velocity:'unknown',velocity_note:'Early stage — insufficient interaction to assess',decision_makers:[{name:'Akhil',role:'Groom',authority:'Primary contact'},{name:'Poorvi',role:'Bride',authority:'Design and vendor decisions'}]},
    actions:[{text:'Schedule first formal planning call with Akhil & Poorvi',priority:'routine'},{text:'Initiate decor moodboard sharing',priority:'routine'}],
    messages:[{sender:'Aditya Sharma',role:'Planner',initials:'AS',color:'#F59E0B',bg:'rgba(245,158,11,0.15)',time:'3 weeks ago',body:'Hi Akhil & Poorvi — excited to be your planner! Will share the planning timeline soon.',negative:false}],
    tl_directive:'Aditya — 29568 is healthy and far out. Schedule the first formal call in May.',
    suggested_client_reply:{drafted_for:'Aditya Sharma',to:'Akhil & Poorvi',body:'Hi Akhil & Poorvi — time to start planning for your February 2027 Wyndham Garden wedding! Could we get on a call this week to kick off? — Aditya'}
  },
  '29662': {
    pid:'29662', couple:'Amrutha · Jay', statusLevel:'attention', statusText:'ATTENTION · 136 days out · No team coverage',
    risk_vectors:[{label:'No Designer or PM',severity:'critical'},{label:'136 Days to Event',severity:'attention'},{label:'Low Collection (12.5%)',severity:'attention'}],
    analysis:['Amrutha & Jay at Gokulam Grand Kerala (Sep 11-13, 2026) is the closest event in Team 4\'s portfolio with 136 days to go. Ananth Santhosh is the planner with <strong>no designer or PM assigned</strong> — a serious gap given the event is in September.','With 12.5% collection on a small ₹2L SP, the financial risk is low but the operational risk of no design or PM support for a September event is high.'],
    team_status:[{role:'Planner',name:'Ananth Santhosh',initials:'AN',color:'#7241BE',bg:'rgba(114,65,190,0.15)',engagement:'Active',last_action:'2 months ago',carrying_signal:'Steady',notes:'Active on Kerala events. Sep event — 136 days out.'},{role:'Designer',name:'.',initials:'?',color:'#F59E0B',bg:'rgba(245,158,11,0.10)',engagement:'Quiet',last_action:'.',carrying_signal:'Steady',notes:'UNASSIGNED — Sep event needs designer in next 30 days'},{role:'PM',name:'.',initials:'?',color:'#F59E0B',bg:'rgba(245,158,11,0.10)',engagement:'Quiet',last_action:'.',carrying_signal:'Steady',notes:'UNASSIGNED'}],
    comms:{client_chattiness:40,client_chattiness_label:'Low',last_client_message:'2 months ago',off_channel_indicator:false,open_commitments:2,open_commitments_detail:['Ananth: assign designer and PM urgently — Sep 2026 is 136 days away','Schedule planning catch-up with Amrutha & Jay']},
    vendor_coverage:[{vendor_type:'Venue',status:'confirmed',note:'Gokulam Grand, Kerala — Sep 11-13, 2026'},{vendor_type:'Decor',status:'unassigned',note:'No designer — 136 days out'}],
    decision_intel:{velocity:'unknown',velocity_note:'Early interactions suggest cooperative couple',decision_makers:[{name:'Amrutha',role:'Bride',authority:'Primary POC'},{name:'Jay',role:'Groom',authority:'Co-decision maker'}]},
    actions:[{text:'URGENT: Assign designer — Sep 2026 event, 136 days out',priority:'critical'},{text:'Schedule May planning call with Amrutha & Jay',priority:'critical'},{text:'Lock key vendors before June — decor, photography',priority:'important'}],
    messages:[{sender:'Amrutha · Jay',role:'Client',initials:'AJ',color:'#8B5CF6',bg:'rgba(139,92,246,0.15)',time:'2 months ago',body:'Hi Ananth — looking forward to the planning process for our Gokulam Grand wedding!',negative:false}],
    tl_directive:'Ananth — 29662 is your most time-pressured unattended project. Sep 11 is 136 days away and you have no designer or PM. Escalate to Amaan immediately.',
    suggested_client_reply:{drafted_for:'Ananth Santhosh',to:'Amrutha & Jay',body:'Hi Amrutha & Jay — with 4.5 months to your Gokulam Grand wedding, it\'s time to accelerate the planning. We\'re finalizing the full team and will be sharing initial vendor options very soon. Could we schedule a call this week? — Ananth'}
  },
  '30969': {
    pid:'30969', couple:'Vivek · Rohini', statusLevel:'healthy', statusText:'HEALTHY · Active couple · Venue discussions ongoing',
    risk_vectors:[{label:'No Designer or PM',severity:'critical'},{label:'Low Collection (10%)',severity:'attention'}],
    analysis:['Vivek & Rohini at Backwater Ripples Kerala (Feb 25-27, 2027) — an NRI couple (Rohini is Dutch) with a cross-cultural wedding. Ananth Santhosh managing with Santosh (venue POC). The couple is engaged and enthusiastic — Rohini added Dutch elements to save-the-date designs.','<strong>No designer or PM assigned</strong> — critical gap for Team 4. However at 10 months out and active planning discussions, the couple is not at risk of disengagement. The cross-cultural wedding (Dutch-Indian) creates interesting design opportunities and slightly higher planning complexity.'],
    team_status:[{role:'Planner',name:'Ananth Santhosh',initials:'AN',color:'#7241BE',bg:'rgba(114,65,190,0.15)',engagement:'Active',last_action:'2 months ago',carrying_signal:'Steady',notes:'Active venue discussions and save-the-date coordination'},{role:'Designer',name:'.',initials:'?',color:'#F59E0B',bg:'rgba(245,158,11,0.10)',engagement:'Quiet',last_action:'.',carrying_signal:'Steady',notes:'UNASSIGNED'},{role:'PM',name:'.',initials:'?',color:'#F59E0B',bg:'rgba(245,158,11,0.10)',engagement:'Quiet',last_action:'.',carrying_signal:'Steady',notes:'UNASSIGNED'}],
    comms:{client_chattiness:60,client_chattiness_label:'Moderate-high',last_client_message:'2 months ago',off_channel_indicator:false,open_commitments:2,open_commitments_detail:['Ananth: share updated save-the-date drafts incorporating Dutch tulip/delftware elements','Santosh: confirm Backwater Ripples room availability']},
    vendor_coverage:[{vendor_type:'Venue',status:'in_progress',note:'Backwater Ripples preferred — some room bookings already there'},{vendor_type:'Save the Date',status:'in_progress',note:'Dutch + Kerala themed — Rohini adding Dutch elements (delftware, tulips)'},{vendor_type:'Decor',status:'unassigned',note:'Cross-cultural Dutch-Kerala theme identified but no designer assigned'}],
    decision_intel:{velocity:'moderate',velocity_note:'Rohini drives creative; Vivek handles logistics; time zone coordination needed (Rohini likely Netherlands-based)',decision_makers:[{name:'Rohini',role:'Bride',authority:'Creative lead — strong aesthetic vision (Dutch + Kerala)'},{name:'Vivek',role:'Groom',authority:'Venue and logistics decisions'}]},
    actions:[{text:'Assign designer for Dutch-Kerala themed wedding — creative concept needs specialist',priority:'critical'},{text:'Share updated save-the-date designs with Dutch elements',priority:'important'},{text:'Confirm Backwater Ripples room availability and finalize venue',priority:'important'}],
    messages:[{sender:'~ Rohini Lachman',role:'Bride',initials:'RL',color:'#8B5CF6',bg:'rgba(139,92,246,0.15)',time:'Mar 17',body:'Good morning! I added two new pictures in google drive for the save the date options :)',negative:false},{sender:'Ananth Santhosh',role:'Planner',initials:'AN',color:'#7241BE',bg:'rgba(114,65,190,0.15)',time:'Mar 18',body:'I just saw those — adding Dutch elements (delftware and tulips) to complement your outfits. Lemme know what you think!',negative:false}],
    tl_directive:'Ananth — 30969 is your most creatively interesting project. Rohini has a clear Dutch-Kerala vision and strong aesthetic engagement. Assign a designer who can handle cross-cultural wedding design.',
    suggested_client_reply:{drafted_for:'Ananth Santhosh',to:'Rohini & Vivek',body:'Hi Rohini & Vivek — sharing the updated save-the-date designs with the Dutch elements you added! We\'ve incorporated the delftware and tulip motifs alongside the Kerala theme. Would love to do a quick call to align on next steps! — Ananth'}
  }
}
